import { useState, type FormEvent, type ReactNode } from 'react';
import { Check, Pencil, Trash2 } from 'lucide-react';
import type { Evidence, Medication, ProviderPreference } from '../shared/contracts';

function EditField({ label, children, wide = false }: { label: string; children: ReactNode; wide?: boolean }) {
  return <label className={`field ${wide ? 'field-wide' : ''}`}><span className="field-label">{label}</span>{children}</label>;
}
function manualEvidence(previous: Evidence[] = []): Evidence[] {
  return [...previous.filter(item => item.method !== 'user_entered'), { id: crypto.randomUUID(), source: 'You', method: 'user_entered', confirmed: true }];
}
export function ProviderEditor({ provider, onChange, onRemove }: { provider: ProviderPreference; onChange: (provider: ProviderPreference) => void; onRemove: () => void }) {
  const [editing, setEditing] = useState(false);
  function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const name = String(data.get('name') ?? '').trim(); if (!name) return;
    onChange({ ...provider, name, npi: String(data.get('npi') ?? '').trim() || undefined, specialty: String(data.get('specialty') ?? '').trim() || undefined, location: String(data.get('location') ?? '').trim() || undefined, evidence: manualEvidence(provider.evidence) });
    setEditing(false);
  }
  return <div className="record-item"><div className="record-row"><label className="record-select"><input type="checkbox" checked={provider.preferred} onChange={event => onChange({ ...provider, preferred: event.target.checked })} /><span><strong>{provider.name}</strong><small>{[provider.specialty, provider.location].filter(Boolean).join(' · ') || 'Provider details not yet added'}{provider.npi ? ` · NPI ${provider.npi}` : ' · No NPI supplied'}</small></span></label><button className="icon-button" onClick={() => setEditing(current => !current)} aria-label={`Edit ${provider.name}`} aria-expanded={editing}><Pencil size={15} /></button><button className="icon-button subtle" onClick={onRemove} aria-label={`Remove ${provider.name}`}><Trash2 size={16} /></button></div>{editing && <form autoComplete="off" className="record-inline-edit" onSubmit={save}><div className="form-grid"><EditField label="Provider name" wide><input name="name" required autoFocus defaultValue={provider.name} maxLength={200} /></EditField><EditField label="Specialty"><input name="specialty" defaultValue={provider.specialty} maxLength={100} /></EditField><EditField label="Location"><input name="location" defaultValue={provider.location} maxLength={250} /></EditField><EditField label="NPI (10 digits)" wide><input name="npi" inputMode="numeric" pattern="[0-9]{10}" maxLength={10} defaultValue={provider.npi} placeholder="If known" /></EditField></div><div className="inline-actions"><button type="button" className="button button-quiet" onClick={() => setEditing(false)}>Cancel</button><button type="submit" className="button button-primary"><Check size={15} /> Save details</button></div></form>}</div>;
}
export function MedicationEditor({ medication, onChange, onRemove }: { medication: Medication; onChange: (medication: Medication) => void; onRemove: () => void }) {
  const [editing, setEditing] = useState(false);
  function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const name = String(data.get('name') ?? '').trim(); if (!name) return;
    onChange({ ...medication, name, strength: String(data.get('strength') ?? '').trim() || undefined, form: String(data.get('form') ?? '').trim() || undefined, rxnorm: String(data.get('rxnorm') ?? '').trim() || undefined, ndc: String(data.get('ndc') ?? '').trim() || undefined, quantity: data.get('quantity') ? Number(data.get('quantity')) : undefined, daysSupply: data.get('daysSupply') ? Number(data.get('daysSupply')) : undefined, evidence: manualEvidence(medication.evidence) });
    setEditing(false);
  }
  return <div className="record-item"><div className="record-row"><label className="record-select"><input type="checkbox" checked={medication.ongoing} onChange={event => onChange({ ...medication, ongoing: event.target.checked })} /><span><strong>{medication.name}</strong><small>{[medication.strength, medication.form, medication.rxnorm ? `RxNorm ${medication.rxnorm}` : medication.ndc ? `NDC ${medication.ndc}` : 'No medication code supplied', medication.quantity ? `Quantity ${medication.quantity}` : '', medication.daysSupply ? `${medication.daysSupply}-day supply` : ''].filter(Boolean).join(' · ')}</small></span></label><button className="icon-button" onClick={() => setEditing(current => !current)} aria-label={`Edit ${medication.name}`} aria-expanded={editing}><Pencil size={15} /></button><button className="icon-button subtle" onClick={onRemove} aria-label={`Remove ${medication.name}`}><Trash2 size={16} /></button></div>{editing && <form autoComplete="off" className="record-inline-edit" onSubmit={save}><div className="form-grid"><EditField label="Medication name" wide><input name="name" required autoFocus defaultValue={medication.name} maxLength={200} /></EditField><EditField label="Strength"><input name="strength" defaultValue={medication.strength} maxLength={80} /></EditField><EditField label="Form"><input name="form" defaultValue={medication.form} maxLength={80} /></EditField><EditField label="RxNorm code"><input name="rxnorm" inputMode="numeric" pattern="[0-9]+" defaultValue={medication.rxnorm} maxLength={30} /></EditField><EditField label="NDC code"><input name="ndc" inputMode="numeric" pattern="[0-9-]+" defaultValue={medication.ndc} maxLength={30} /></EditField><EditField label="Quantity per fill"><input name="quantity" type="number" min="0" max="100000" step="any" onChange={event => event.target.setCustomValidity(!event.target.value || Number(event.target.value) > 0 ? '' : 'Enter a quantity greater than zero.')} defaultValue={medication.quantity} /></EditField><EditField label="Days supplied per fill"><input name="daysSupply" type="number" min="1" max="366" step="1" defaultValue={medication.daysSupply} /></EditField></div><div className="inline-actions"><button type="button" className="button button-quiet" onClick={() => setEditing(false)}>Cancel</button><button type="submit" className="button button-primary"><Check size={15} /> Save details</button></div></form>}</div>;
}
